---
title: "Preparación y análisis de experimentos"
description: "Licenciatura en Manejo Sustentable de la Zona Costera"
author: "Gerardo Martín"
output:
      distill::distill_article:
            self_contained: false
---

# Introducción al diseño experimental

1. [Tipos de experimentos y observaciones](Unidad 1-Introducción/Tipo-exper-observ.html)

2. [El concepto de dato](Unidad 1-Introducción/Concepto-dato.html)

3. [La unidad experimental](Unidad 1-Introducción/Unidad-exper.html)

4. [Réplica, control y pseudo-replicación](Unidad 1-Introducción/Replica-control.html)

5. [Bloques y balance](Unidad 1-Introducción/Bloques-balance.html)

# El modelo ANOVA de una vía

1. [Introducción a ANOVA](Unidad 2-ANOVA I/ANOVA-I.html)

2. [Diseño completamente aleatorizado con efectos fijos](Unidad 2-ANOVA I/Diseño-aleat-fijos.html)

      2.1. [Tutorial de R](Unidad 2-ANOVA I/Tutorial-R.html)

3. [Diseño completamente aleatorizado con efectos aleatorios](Unidad 2-ANOVA I/Diseño-efect-aleat.html)

4. [Diseño completamente aleatorizado con bloques al azar](Unidad 2-ANOVA I/Bloques-aleatorios.html)

      4.1 [Tutorial de R-2](Unidad 2-ANOVA I/Tutorial-R-2.html)

5. [Pruebas equivalentes para datos ordenados por rango](Unidad 2-ANOVA I/Kruskal-Wallis.html)

# El modelo ANOVA con dos o más criterios de clasificación

1. [Introducción al modelo ANOVA de dos vías](Unidad 3-ANOVA II/ANOVA-II.html)

2. [Diseño balanceado con efectos fijos](Unidad 3-ANOVA II/Diseño-balance-fijos.html)

3. [Diseño no balanceado con efectos fijos](Unidad 3-ANOVA II/Diseño-no-balance-fijos.html)

4. [Diseños con efectos mixtos (fijos y aleatorios)](Unidad 3-ANOVA II/Diseño-efectos-mixtos.html)

5. [Interpretación de las interacciones](Unidad 3-ANOVA II/Interpretacion-interacciones.html)

6. [Generalización a modelos con más criterios de clasificación](Unidad 3-ANOVA II/Generalizacion-disenos-factoriales.html)

# Otros diseños frecuentemente usados

1. [Diseños "split-plot" (parcelas divididas)](Unidad 4-Otros disenos/Split-plot.html)

      1.1. [Presentación de split-plot](Unidad 4-Otros disenos/Split-plot-slides.html)

2. [Cuadrado latino](Unidad 4-Otros disenos/Cuadrado-latino.html)

      2.1. [Características, ventajas y limitaciones](Unidad 4-Otros disenos/Cuadrado-vent-lim-slides.html)

3. [Diseño de medidas repetidas sin réplicas](Unidad 4-Otros disenos/Medidas-repetidas.html)

      3.1 [Medidas repetidas y diseños anidados](Unidad 4-Otros disenos/Medidas-slides.html)

4. [Control asimétrico](Unidad 4-Otros disenos/Control-asimetrico.html)

# Regresión y correlación

1. [Regresión lineal](Unidad 5-Regresion correlacion/Regresion.html)

2. [Regresiones múltiples]

3. [Regresión polinomial]

4. [Análisis de covarianza]

5. [Correlación]